services:
  renovate-executor:
    container_name: renovate-executor
    image: ghcr.io/stefftek/renovate-executor:1.1.2
    ports:
      - 4000:4000
    environment:
      RE_HANDLER: "github"
      RE_RUNTIME: "docker"
      RE_CRON_SCHEDULE: "*/10 * * * *"
      RE_RENOVATE_IMAGE: renovate/renovate:39.49
      RE_RENOVATE_ENV: /tmp/renovate.env.json
      # Custom Config
      RE_GITHUB_TOKEN: ghp_xxxx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./renovate.env.json:/tmp/renovate.env.json