name: Check Build

# Run this workflow on pushes to the main and develop branches, as well as on pull requests and manual triggers
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    permissions:
      contents: read # to be able to publish a GitHub release
      issues: read # to be able to comment on released issues
      pull-requests: read # to be able to comment on released pull requests
      security-events: write # to be able to publish security events
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      # Run linting, formatting, and build steps
      - name: Format, Lint and Build App
        run: npm run build

      # Run Trivy Vulnerability Scan
      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: trivy.yaml
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          token: ${{ secrets.GITHUB_TOKEN }}